; SPDX-License-Identifier: AGPL-3.0-or-later
; This file is part of the Spazio IT Video-to-Knowledge project.

[openai]
base_url = http://localhost:8080/api
api_key = sk-xxxxxxxxxxxxxxxxxxxxxxx
vmodel_name = medgemma-1.5:4b

